### ISSUE TITLE
Fetchr.registerFetcher is not a function

### ISSUE THREAD

**Issue by kosmotaur** [yahoo/fluxible-plugin-fetchr#20]
When trying to register a new fetcher like this:

```js
var fetchrPlugin = require('fluxible-plugin-fetchr');
var fetchr = fetchrPlugin({
  xhrPath: '/api'
});
var dummyFetcher = {
  name: 'dummy',
  read: function(req, resource, params, config, callback) {
    console.log('Reading from dummy fetcher');
  }
};

fetchr.registerService(dummyFetcher);
```

I get an error like in the title. This is happening here: https://github.com/yahoo/fluxible-plugin-fetchr/blob/master/lib/fetchr-plugin.js#L124

**Comment by lingyan** [comment]
@kosmotaur This might help: https://github.com/yahoo/fluxible-plugin-fetchr/issues/17

**Comment by kosmotaur** [comment]
Thanks, looks similar indeed. 
I guess in my case it is rather caused by trying to register a service with custom CRUD methods client-side. Requiring Fetchr there gives me the export from `fetcher.client.js`, which doesn't have the `registerService` method.
Is it possible/feasible at all to implement my own CRUD methods on the client?

**Comment by lingyan** [comment]
##### Let me try to explain the flow of data fetching using Fetchr first:
`Fetchr` is created for providing a way to allow uniform syntax for fetching data on client and server side.  All client-side data fetching requests through `Fetchr` are "proxied" to server-side, and actual data fetching from back-end data sources executes on the server side.

`registerService` is only supposed to be called on server side, like what is in our chat example: https://github.com/yahoo/flux-examples/blob/master/chat/server.js#L29  It basically establishes a mapping that maps any resource name to its corresponding fetcher service.

A fetchr service manager is [exposed to actions](https://github.com/yahoo/fluxible-plugin-fetchr/blob/master/lib/fetchr-plugin.js#L82) via action context's `context.service`, by fluxible-plugin-fetchr, for both client and server.

The trick is the fetchr service manager instances created on client and server are actually different.  The [client-side manager instance](https://github.com/yahoo/fetchr/blob/master/libs/fetcher.client.js) proxies all data requests via XHR to a single api endpoint powered by [fetchr middleware](https://github.com/yahoo/fetchr#1-middleware).  (The middleware is [applied to](https://github.com/yahoo/flux-examples/blob/master/chat/server.js#L31) the express server as part of server setup in `server.js`.)

Each request sent over the wire via XHR conforms to a predefined protocol, where `resource`, `operation`, `params`, `body` are part of the request.  When the request gets to the server side, the server side Fetchr service manager [looks up the actual registered fetcher service from the resource name -> servier mapping and routes](https://github.com/yahoo/fetchr/blob/master/libs/fetcher.js#L155) the request to it.

You can check out [Fetchr docs](https://github.com/yahoo/fetchr#fetchr) for more details about how `Fetchr` works.

##### If your app wants to fetch data on client side without going through Fetchr flow:
You can always create your own plugin for data fetching, similar to [fluxible-pluging-fetchr](https://github.com/yahoo/fluxible-plugin-fetchr), exposes it to action context.  Just be careful that, if actions using it can be run on both client/server, you will need to make sure it works for both.

**Comment by kosmotaur** [comment]
Thanks so much, it makes perfect sense now. Initially it was not obvious to me that this Fluxible plugin was supposed to only work in a strict server/client setup.

That being said, do you have any idea on how to implement a custom way of actually kicking off the XHR client-side? The reason being I wanted to use Oboe to progressively update the views as data streams in, but I see Fetchr has it's own implementation baked in and doesn't expose extensibility means to override it.
