### ISSUE TITLE
response cookies not in response

### ISSUE THREAD

**Issue by mwelche** [yahoo/fluxible-plugin-fetchr#24]
I'm making a request to an API server for login, and the API server sends back a response cookie with an auth token thats used to check auth throughout the app. However, the response cookie seems to get caught at the service proxy and isnt in the response.

**Comment by mridgway** [comment]
You can set response headers for ajax requests by sending a third parameter to your service's callback:

```js
Service.read = function (req, resource, params, config, callback) {
    // ...
    callback(null, data, { headers: { Foo: ‘bar’ } });
};
```

In your case, you could even just send the response headers there.

**Comment by mwelche** [comment]
great, thanks for the tip
