### ISSUE TITLE
Correctly work with arguments

### ISSUE THREAD

**Issue by AVVS** [yahoo/fluxible-plugin-fetchr#28]
For instance `var args = Array.prototype.slice.call(arguments);` prevent function from being optimized by VM.

More on the topic here: https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#3-managing-arguments

**Comment by Vijar** [comment]
@AVVS Wow, looks to be quite a significant hit: http://jsperf.com/copy-fn-arguments-test

**Comment by AVVS** [comment]
basically the only thing that is safe to use is arguments.length and arguments[i] + smth.apply(context, arguments)

these cases are covered, the rest are super slow compared to them

**Comment by escalona** [comment]
@AVVS Good to know. I've created a PR with the change proposed in the linked doc. #30

**Comment by Vijar** [comment]
Fixed by @escalona in #30
