### ISSUE TITLE
Using Fetchr's CORS functionality with fluxible-plugin-fetchr?

### ISSUE THREAD

**Issue by neilius** [yahoo/fluxible-plugin-fetchr#31]
I'm interested in using the CORS functionality of Fetchr in my Fluxible project, yet nothing in this repo's documentation references the CORS functionality and I don't see it anywhere within the source. Is it currently possible to use Fetchr's CORS functionality with this plugin?

**Comment by redonkulus** [comment]
@neilius have you seen this part of the Fetchr readme? https://github.com/yahoo/fetchr#3-api-cors-support

**Comment by neilius** [comment]
@redonkulus Yes, that's what I'm referring to, but it's unclear to me how that functionality integrates with this plugin. I've tried the following:

```
// from my app.js
app.plug(fetchrPlugin({
    xhrPath: "/api",
    corsPath: "http://example.com/api"
}));

// from one of my services
module.exports = {
    name: "posts",
    cors: true,

    read: function(req, resource, params, config, done) {
         // api request stuff here
    }
};
```

That didn't result in the CORS request taking place as I might have expected so that's what I'm trying to get a little more insight into.

**Comment by escalona** [comment]
@neilius the "cors: true" flag is passed in as the config parameter when your service is called, it's not an option on the service itself.

``` 
fetcher.read('service', {}, {cors: true,}, callbackFn);
```

**Comment by redonkulus** [comment]
Correct @escalona, you can see that in the example: https://github.com/yahoo/fetchr#cors-support

**Comment by Vijar** [comment]
@neilius `fluxible-plugin-fetchr` merely maps the read(and other crud methods) from the `fetchr` package into `fluxible`'s `actionContext`.

So, the `this.service.read` method in your action automatically supports all the arguments that are described in the `fetchr` documentation pointed to above.

**Comment by neilius** [comment]
Ok, I've got it (mostly) working now, or at least it's now calling my own version of `constructGetUri` when I pass `cors: true` and my own `constructGetUri` function into the read call from the action context. That gets me 98% of the way there. The `uri` parameter passed in to constructGetUri, however, is `undefined`. If I'm understanding things correctly, that value should be my `corsPath`, correct? Or am I misunderstanding what that parameter should be? Is that a bug or a step of configuration I've missed? If that's on my end, feel free to close.

Thanks all for the help all!

**Comment by koulmomo** [comment]
cc @longlho

**Comment by escalona** [comment]
It looks like fetchr-plugin doesn't accept a corsPath in its options. In this case, the `uri` parameter should be your xhrPath.

**Comment by Vijar** [comment]
@neilius You're right, it should be set to your `corsPath` but that is never passed in as @escalona 
pointed out. This is a bug, will be fixed shortly.

**Comment by escalona** [comment]
@Vijar Took a shot at fixing this: #32

**Comment by Vijar** [comment]
@escalona thats pretty much how I was going to do it, until I noticed the logic duplication issue :-/ not sure if there is a way around it though.

**Comment by neilius** [comment]
Awesome... I greatly appreciate the rapid response!

**Comment by Vijar** [comment]
@neilius this should be fixed in the latest version.
