### ISSUE TITLE
Service look up returns "404 not found" when invoked from Client.

### ISSUE THREAD

**Issue by raviksha** [yahoo/fluxible-plugin-fetchr#35]
I have an app which has a registered service which is invoked and executed as expected on the initial pay load(i.e when called from initAction() on the server.

The same service when invoked from an action via the componentDidUpdate() {this.context.executeAction(loadIndex);} thows a 404 not found.

As the requirements I have - 
1. Registered the service on the sever.js -
var server = express();
fetchr.registerService(require("./service/localeService"));

2. Have set up the fetchr middleware using -
server.use(fetchr.getXhrPath(), fetchr.getMiddleware());

3. The app context is created as follows  in the server.js-
    var context = app.createContext({
        req: req, // The fetchr plugin depends on this      
    });
4. On the app.js have set up the xhrPath as -
app.plug(fetchrPlugin({ xhrPath: "/api" }));

5. The 'fluxible-plugin-routr' is configured to use the config/routes.js -
import routrPlugin from 'fluxible-plugin-routr';
import routes from './configs/routes';
app.plug(routrPlugin({
    routes: routes
}));

Now when the event is fired from the component the look up url is -
http://hostname:6060/api/localeService <NetworkError: 404 Not Found>

On tracing the issue in debugger, the controls goes upto -  fetcher-plugin.js ==> fetcherCLient.js ===> httpClient.js -

function io(url, options) {
    xhr({
        url: url,   ======>>> (/api/localeService)
        method: options.method =====> METHOD_GET,
        timeout: options.timeout,
        headers: options.headers,
        {X-Requested-With =====> "XMLHttpRequest"
         useXDR ===>  undefined}
        body: options.data,
        useXDR: options.cors
    }

Why isnt the server able to look up the registered service at "(/api/localeService)" ?

It doesn't make sense to have this path needs to be defined in the config/route.js ?

**Comment by raviksha** [comment]
The versions of the npm modules -
        "express-state": "^1.2.0",
        "flux-router-component": "^0.6.0",
        "fluxible": "^0.4.12",
        "fluxible-plugin-fetchr": "^0.3.3",
        "fluxible-plugin-routr": "^0.3.0",

**Comment by Vijar** [comment]
@raviksha I see that you're registering the service via `fetchr.registerService(require("./service/localeService"));` but how are you defining the `fetchr` variable?

Do you have `var fetchr = app.getPlugin('FetchrPlugin');`?

**Comment by raviksha** [comment]
const fetchr = app.getPlugin("FetchrPlugin");  This is how I have defined in my server.js

**Comment by Vijar** [comment]
Hmm, I see.

If you start your server with debug enabled(`DEBUG=Fetchr node server.js`) do you see the line `'fetcher localeService added` in the debug messages on the server log?

**Comment by raviksha** [comment]
When i run in debug mode I see all my services registered in the server logs-
  Fetchr fetcher productService added +0ms
  Fetchr fetcher userService added +2ms
  Fetchr fetcher translationService added +2ms
  Fetchr fetcher localeService added +1ms


On the browser console I also see -

Fluxible:FetchrPlugin service proxy +5s
js.js (line 273)
Fetcher:defaultConstructGetUri constructed get uri: +2s /api/productService
js.js (line 273)
GET http://<hostname>6060/api/productService
	
404 Not Found
		161ms	
js.js (line 39045)
"NetworkError: 404 Not Found - http://<hostname>:6060/api/productService"
productService
FetchrClient Syncing productService failed: statusCode=404 +2s info FetcherClient
js.js (line 273)
Fluxible:FetchrPlugin service proxy callback +3ms undefined undefined
js.js (line 273)
Fluxible:Context Executing action componentActionHandler with payload +3ms Object { err=Error: Error 404}

**Comment by Vijar** [comment]
`http://:6060/api/productService` isn't really a valid URL. Did you remove the hostname for privacy reasons or is this the URL actually generated by fetchr?

**Comment by raviksha** [comment]
sorry my bad .... the url is actually - http://<hostname>:6060/api/productService  OR http://<hostname>:6060/api/localeService

**Comment by Vijar** [comment]
Then it looks like the hostname is empty for some reason. Are you developing this locally?

At what url do you access your app's main page? Something like `http://localhost:6060/`?

**Comment by raviksha** [comment]
@Vijar , looks like any text between &lt;   and &gt; is auto stripped obvious for security reasons .....
My url is of the format as u have mentioned and instead of 'localhost' its my 'hostname.'

The flow is working now ....  The issue was that the sever module was not exported correctly. 
Instead of - module.exports.server = server; I was exporting it as module.exports.handleRequest
where handleRequest was the top level method in the server.js

This was not making the fetcher middle ware receive the requests from client. With the above change now its working as expected .

Thank you !!
