### ISSUE TITLE
Outdated "fetchr" dependency

### ISSUE THREAD

**Issue by rbpinheiro** [yahoo/fluxible-plugin-fetchr#40]
The version currently being used fails to parse JSON on the client side if the content-type includes the charset.
This and other bugs have been fixed on newer versions of Fetchr.

If anyone else is having this bug, this is a temporary fix that will work on server and client till the dependency is updated:
```
context.service.read('Product', {}, {}, (err, data) => {
  ....
  context.dispatch('PRODUCTS_LOADED', {
     products: (data.body) ? data.body.data : JSON.parse(data.text).data
  });
  ...
});
```

**Comment by redonkulus** [comment]
@rbpinheiro the package.json of this packages points to the latest from fetchr. Which version of npm are you using? It might be related to the fact we are using the carat (^) to specify the dependency.

**Comment by rbpinheiro** [comment]
@redonkulus the npm version on my machine is 2.1.11

Are you sure it points to the latest from fetchr?
Here I see the version "^0.5.7" --> https://github.com/yahoo/fluxible-plugin-fetchr/blob/master/package.json
But on fetchr releases I can see the v0.5.12 as the latest --> https://github.com/yahoo/fetchr/releases

**Comment by mridgway** [comment]
`^0.5.7` will pick up 0.5.12 when you run install on a fresh check out (try it out on http://semver.npmjs.com/). If you already have 0.5.7 installed, it won't reinstall. I agree we should upgrade the dependency, but you should be able to run a fresh install to get it to work for now.
