### ISSUE TITLE
MultipartFile request using superagent.

### ISSUE THREAD

**Issue by raviksha** [yahoo/fluxible-plugin-fetchr#44]
I am trying to submit a multi part File request in the following way -
Inside the component -
<input ref= "fileImport" name="File" className="file-input" type="file" onChange={this.onChangeFileImport.bind(this)}/>

onChangeFileImport(e){
        var file = e.currentTarget.files;
      if (file && 0 < file.length) {
            console.log("FileName to upload" + file[0]);           
            this.context.executeAction(importTerm, {
                payload: this.props.navigate,
                formData: e.currentTarget.value,
                username: this.props.userName,
                productName: this.state.productName
            });
        }
    }

 request.post(url)
            .field('file', query.formData)
            .attach('file', query.formData)
            .set('Accept', 'application/json')
            .end((err, res) => {
            console.log("Received response %s from %s", res && res.status, url);

            if (err) {
              if (err.status) {
                err.statusCode = err.status;
              }
                return done(err);
            }
            done(null, res.body);
        });

I get the following error - 
>> 
>> stream.js:94
>> throw er; // Unhandled stream error in pipe.
>>             ^
>> Error: ENOENT, open 'C:\fakepath\JSON_New_1.html'

I understand the fact that the file path is intentionally hidden with a fake one but behind the scene it would be able to refer to the actual file. 

Any pointers or examples of what I could be doing wrong here ?  Is this output expected ?

I am using super-agent , with the documentation mentioned here -
http://visionmedia.github.io/superagent/#multipart-requests

Thanks

**Comment by Vijar** [comment]
@raviksha what does your code `console.log("FileName to upload" + file[0]);` output?

**Comment by Vijar** [comment]
Based on the [react-file-input](https://github.com/captivationsoftware/react-file-input/blob/4542b2c5500e6e4d1fafe2dd2e882ac2996d5b38/lib/index.js#L29) library I would also try to replace your `e.currentTarget.value` with `e.target.value.split(/(\\|\/)/g).pop()` and see if that helps.

**Comment by raviksha** [comment]
@Vijar , I tried with your changes but the result is still d same.  The reason is that currently fetcher middle ware is not having support for file upload. If I use a different middle ware with express, i.e "body-parser": "^1.6.4", this works fine. Closing the issue for now !

**Comment by maiopirata** [comment]
@raviksha, I'm stuck with the same problem, I do not understand how to use the body-parser middelware directly.
In my component my code is similar to yours:

	submitFile: function(){
		var formData = new FormData();
		formData.append("file", this.state.fileUploaded);
		// console.log(formData.get("file"));

		this.context.executeAction(fileUploadSrv, {
			"token": this.props.token, 
			"formData": formData
		});

**Comment by maiopirata** [comment]
in my action I do:
```javascript
request.post(url)
    .type('form')
    .field('token', payload.token)
    .attach("file", payload.formData)
    .end((err,res) => {
      console.log("Received response %s from %s", res && res.status, url);
      if (err) {
        if (err.status) {
          err.statusCode = err.status;
        }
        return done(err);
      }
      done(null, res.body);
    })
```
how can use body.parser in order to make it work?

**Comment by raviksha** [comment]
@maiopirata -   Instead of using the route via the action context inside the Component class, I used direct XHR request like - 
xhr.open("POST", 'mypath/api/upload/?productName='

Then in the server.js I added another entry other than the default one to honor this path like - 
server.use("/api/upload", function handleRequest(req, res, next) {
 
    var context = app.createContext({
        req: req, // The fetchr plugin depends on this      
    });
    let params = {
        url: req.originalUrl,
        byId: req.currentUserId,
        expertUser: req.expertUser,
        cookie: req.cookies,
	formData: req.files,

    }
    context.getActionContext().executeAction(importTerm, params, (err) => {
        if (err) {
            console.log("Err" + err);
            res.end("ERROR");
        }else{
            res.end("OK");
        }
        console.log("Response ended");
    });

});

If you have the body parser included in your dependencies installed you shud get the value for the param - 
formData: req.files;

And the I post the file to the actual end point as - 

importTermFromFile : function(endpoint, query, { cookie }, done) {  
        const url = endpoint + 'uri?rootName=' + query.productName + '&fileName=Test';
        cookie = normalizeCookies(cookie);
        request.post(url, query.formData)
            .set('cookie', cookie)
            .field("file", query.formData.File.originalFilename)
            .attach('file', query.formData.File.path)
            .end((err, res) => {
            console.log("Received response %s from %s", res && res.status, url);
            if (err) {
              if (err.status) {
                err.statusCode = err.status;
              }
                return done(err);
            }
            done(null, res.body);
        });
    }

**Comment by raviksha** [comment]
Hope that helps ...
