### ISSUE TITLE
400 Error: when I try to use create from service

### ISSUE THREAD

**Issue by sathify** [yahoo/fluxible-plugin-fetchr#46]
I have a DataService issue when I try to use the create method from the service. I also tried using a postman client to verify and I get the same error so not sure what is going on. The read method works fine. My service looks similar to [this](https://github.com/porchdotcom/isomorphic-porch-demo/blob/master/server/services/project-service.js). Very much appreciate any valuable pointers on the issue. 

```
HttpError
   at Object.<anonymous> (/Users/satheesh/dev/rackudos/node_modules/fluxible-plugin-fetchr/node_modules/fetchr/node_modules/fumble/HttpError.js:28:23)
   at Module._compile (module.js:456:26)
   at Module._extensions..js (module.js:474:10)
   at Object.require.extensions.(anonymous function) [as .js] (/Users/satheesh/dev/rackudos/node_modules/babel-core/lib/api/register/node.js:214:7)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous> (/Users/satheesh/dev/rackudos/node_modules/fluxible-plugin-fetchr/node_modules/fetchr/node_modules/fumble/libs/fumble.http.js:8:17)
   at Module._compile (module.js:456:26)
```

**Comment by mridgway** [comment]
How are you calling the service?

**Comment by sathify** [comment]
@mridgway thanks! I'm executing the below action in the component's `onSave`.


```
import KudosStore from '../stores/KudosStore';

export default function createKudo(actionContext, payload, done) {

    const kudosStore = actionContext.getStore(KudosStore);
    const newKudo = kudosStore.createKudo(payload);

    actionContext.dispatch('CREATE_KUDO_START', newKudo);

    actionContext.service.create('KudosService', newKudo, {}, (err, kudo) => {
        if (err) {
            console.error(err);
            actionContext.dispatch('CREATE_KUDO_FAILURE', newKudo);
            done(err);
            return;
        }

        /*
         * Dispatches the event passing along the kudo to all stores registered
         * to handle this event.
         */
        actionContext.dispatch('CREATE_KUDO_SUCCESS', kudo);
        done();
    })

}
```

**Comment by mridgway** [comment]
Weird, the error isn't very helpful and the stack trace doesn't seem to have any lines within Fetchr.

**Comment by Vijar** [comment]
@sathify In your service did you define the create method with all five arguments? `create: function(req, resource, params, body, config, callback) {`?

Also you can do a try/catch block around your `actionContext.service.create` call and try to log the `err.satusCode`, `err.message`, and `err.debug` properties for more debugging info.

**Comment by sathify** [comment]
Yeah my create method looks fine with all arguments.

![screen shot 2015-09-01 at 3 33 27 pm](https://cloud.githubusercontent.com/assets/860123/9618907/42465030-50bf-11e5-824e-18b9c76dd062.png)

Network tab:

![screen shot 2015-09-01 at 3 34 10 pm](https://cloud.githubusercontent.com/assets/860123/9618915/54c2c0f4-50bf-11e5-9f7a-ca98e55041ca.png)

Error:

![screen shot 2015-09-01 at 3 37 50 pm](https://cloud.githubusercontent.com/assets/860123/9618975/fc49d4e8-50bf-11e5-9e09-36d2685b171b.png)

**Comment by Vijar** [comment]
@sathify I'm able to reproduce this and am debugging right now.

**Comment by sathify** [comment]
@Vijar thanks much. Hopefully it's a quick fix.

**Comment by Vijar** [comment]
@sathify So I may have reproduced a different error, but I got rid of it by wiping out `node_modules` and reinstall everything. I think my error was caused by outdated deps. Can you verify that you're on the latest `fluxible-plugin-fetchr` and `fetchr` packages?

Also, are you using chaining `(service.read('KudosService').params(...).end(...)` anywhere in your code? There are some bugs with that I believe.

**Comment by sathify** [comment]
@Vijar I got rid of it by wiping out node_modules and reinstalling everything as well and still have the same problem. Does` fluxible-plugin-fetchr` depend on `fetchr` beacuse I'm not using `fetchr`.

Also, no not chaining.

**Comment by Vijar** [comment]
After talking offline, we determined the reason for the error was not using `body-parser`. @sathify will make a PR to the README to make it obvious that `body-parser` is needed before `fluxible-plugin-fetchr` will work.

Also yahoo/fumble#10 will provide a better stack trace in the future to make debugging easier.
